fruits=[]
f1=input("enter the fruit name :")
fruits.append(f1)
f2=input("enter the fruit name :")
fruits.append(f2)
f3=input("enter the fruit name :")
fruits.append(f3)
f4=input("enter the fruit name :")
fruits.append(f4)
f5=input("enter the fruit name :")
fruits.append(f5)
print(fruits)