marks=[]
m1=input("enter marks:")
marks.append(m1)
m2=input("enter marks:")
marks.append(m2)
m3=input("enter marks:")
marks.append(m3)
m4=input("enter marks:")
marks.append(m4)
m5=input("enter marks:")
marks.append(m5)
marks.sort()
print(marks)